name: "Increment Version"
description: "An action that controls version increment for CI's"
inputs:
  app-id:
    description: "GitHub App ID used to generate the token"
    required: true
  private-key:
    description: "GitHub App private key"
    required: true
  current-version-variable:
    description: "Current version repository variable containing the project version (format: MAJOR.MINOR.PATCH)"
    required: true
    default: CURRENT_VERSION
runs:
  using: "composite"
  steps:
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
      shell: bash
    - name: Generate GitHub App token
      id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
    - name: Increment version
      run: |
        curl \
          -H "Authorization: Bearer $APP_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/variables/${{ inputs.current-version-variable }} \
          -w "%{http_code}" 
      shell: bash
    - name: Update CURRENT_VERSION variable
      env:
        APP_TOKEN: ${{ steps.app-token.outputs.token }}
      run: |
        curl -X PATCH \
          -H "Authorization: Bearer $APP_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/variables/${{ inputs.current-version-variable }} \
          -d "{\"name\":\"${{ inputs.current-version-variable }}\",\"value\":\"${{ env.NEW_VERSION }}\"}"
      shell: bash
