name: "Candango Increment Version"
description: "An action that controls version increment for CI's"
inputs:
  app-id:
    description: "GitHub App ID used to generate the token"
    required: true
  private-key:
    description: "GitHub App private key"
    required: true
  current-version-variable:
    description: "Current version repository variable name containing the project version"
    required: true
    default: CURRENT_VERSION
runs:
  using: "node20"
  main: "dist/index.js"
