name: Test increment version
on: [push]

jobs:
  test-python:
    runs-on: ubuntu-latest
    if: github.repository == 'candango/increment-version'
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
      - name: Create mock Python version file
        run: |
          cat <<EOF > mock_init.py
          __version__ = (0, 0, 1)
          
          def get_version():
              if isinstance(__version__[-1], str):
                  return '.'.join(map(str, __version__[:-1])) + __version__[-1]
              return ".".join(map(str, __version__))
          EOF
      - name: Run Action (Local - Python)
        id: increment
        uses: ./
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          language: python
          file-path: mock_init.py
          is-prerelease: true
          prerelease-type: a
      - name: Verify Python update
        run: |
          echo "Content of mock_init.py:"
          cat mock_init.py
          EXPECTED_VERSION="${{ steps.increment.outputs.new-version }}"
          ACTUAL_VERSION=$(python3 -c "import mock_init; print(mock_init.get_version())")
          echo "Expected: $EXPECTED_VERSION"
          echo "Actual: $ACTUAL_VERSION"
          if [ "$EXPECTED_VERSION" != "$ACTUAL_VERSION" ]; then
            echo "Version mismatch!"
            exit 1
          fi
          echo "Python Ghost Update Verified via get_version()!"

  test-js:
    runs-on: ubuntu-latest
    if: github.repository == 'candango/increment-version'
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
      - name: Run Action (Local - JS)
        id: increment
        uses: ./
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          language: javascript
          is-prerelease: true
          prerelease-type: b
      - name: Verify JS update
        run: |
          NEW_VERSION="${{ steps.increment.outputs.new-version }}"
          echo "Verifying if $NEW_VERSION is in package.json..."
          cat package.json | grep "$NEW_VERSION"
          echo "JS Ghost Update Verified!"
