name: Test increment version
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - uses: ./
        with:
          who-to-greet: "A Piraz!!!"
      - run: echo "Greet time at ${{ steps.test.outputs.time }}"
        id: test
